language: go

go:
  - 1.12.x
  - 1.13.x
  - tip

before_install:
  - go get -v golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - go get -t ./...

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint ./...)
  - go test -v -race -covermode=atomic -coverprofile=cover.out ./...
  - goveralls -coverprofile=cover.out -service=travis-ci

matrix:
  allow_failures:
    - go: tip
